name: double_tap_back_exit
description: "A Flutter widget to handle double-tap exit functionality with customizable duration and toast/snackbar messages."
version: 1.1.0
homepage: "https://github.com/Marcocholla01/double_tap_back_exit"

environment:
  sdk: ">=3.7.2 <4.0.0"  # Supports Flutter SDK from 3.7.2 up to (but not including) 4.0.0
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

